-- Habilitar extensión uuid-ossp si no está habilitada
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Tabla de Ingresos
CREATE TABLE IF NOT EXISTS public.ingresos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concepto text NOT NULL,
    cantidad double precision NOT NULL,
    comprobante text, -- URL del comprobante
    fecha timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla de Egresos
CREATE TABLE IF NOT EXISTS public.egresos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concepto text NOT NULL,
    cantidad double precision NOT NULL,
    comprobante text, -- URL del comprobante
    fecha timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla de Usuarios (Perfil extendido para Supabase Auth)
CREATE TABLE IF NOT EXISTS public.usuario (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre text NOT NULL,
    rol integer NOT NULL DEFAULT 0, -- ej. 0: Vecino, 1: Administrador, etc.
    telefono text
);

-- RLS (Row Level Security)
ALTER TABLE public.ingresos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.egresos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuario ENABLE ROW LEVEL SECURITY;

-- Políticas básicas (Lectura y Escritura permitidas para usuarios autenticados)
CREATE POLICY "Permitir todo a usuarios autenticados en ingreso" ON public.ingresos
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Permitir todo a usuarios autenticados en egreso" ON public.egresos
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Permitir todo a usuarios autenticados en usuario" ON public.usuario
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Trigger para automatizar la creación del perfil en public.usuario al registrarse en Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.usuario (id, nombre, rol, telefono)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'nombre', 'Usuario Nuevo'),
    0, -- Rol por defecto
    COALESCE(new.raw_user_meta_data->>'telefono', '')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
